import { ANALYSIS_LIMITS } from '../domain/analysis/analysisLimits';
import { ANALYSIS_CATEGORIES, ANALYSIS_CONFIDENCES, ANALYSIS_ERROR_TYPES, ANALYSIS_MODES as CANONICAL_ANALYSIS_MODES } from '../domain/analysis/analysisTypes';

/**
 * Constantes globais do sistema para evitar valores mágicos.
 */
export const APP_CONSTANTS = {
  MAX_CODE_LENGTH: ANALYSIS_LIMITS.maxCodeLength,
  MIN_SUBSTANTIAL_CODE_LENGTH: 10,
  ANALYSIS_COOLDOWN_MS: 10000,

  COLLECTIONS: {
    ATTEMPTS: 'attempts',
    CHALLENGE_PROGRESS: 'challengeProgress',
    SESSIONS: 'sessions',
    EVENTS: 'events',
    USER_PROFILES: 'users',
  },

  ANALYSIS_CATEGORIES: { INITIAL: ANALYSIS_CATEGORIES[0], PARTIAL: ANALYSIS_CATEGORIES[1], ALMOST: ANALYSIS_CATEGORIES[2], ADEQUATE: ANALYSIS_CATEGORIES[3] } as const,

  CONFIDENCE_LEVELS: { LOW: ANALYSIS_CONFIDENCES[0], MEDIUM: ANALYSIS_CONFIDENCES[1], HIGH: ANALYSIS_CONFIDENCES[2] } as const,

  ERROR_TYPES: ANALYSIS_ERROR_TYPES,

  ANALYSIS_MODES: { PRIMARY: CANONICAL_ANALYSIS_MODES[0], SECONDARY: CANONICAL_ANALYSIS_MODES[1], LOCAL_FALLBACK: CANONICAL_ANALYSIS_MODES[2], LEGACY_FALLBACK: CANONICAL_ANALYSIS_MODES[3], UNKNOWN: CANONICAL_ANALYSIS_MODES[4] } as const,

  PROMPT_VERSION: '3.1.0',
};
